#!/usr/bin/env zsh

# Java
export JAVA_HOME=$(/usr/libexec/java_home -v 21)

# Perl
PATH="~/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="~/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="~/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"~/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=~/perl5"; export PERL_MM_OPT;

# Toolbox
if [ -e /Users/stephan.blakeslee/.starling/etc/profile ]; then
  . /Users/stephan.blakeslee/.starling/etc/profile
else
  echo "Could not find '/Users/stephan.blakeslee/.starling/etc/profile'"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# AWS
export AWS_IAM_USERNAME=StephanBlakeslee

# GCP
export GOOGLE_CREDENTIALS=$(cat $HOME/.config/gcloud/application_default_credentials.json)
if [ -f '/Users/stephan.blakeslee/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/stephan.blakeslee/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/stephan.blakeslee/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/stephan.blakeslee/google-cloud-sdk/completion.zsh.inc'; fi

# Colours
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[0;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'

# Misc. Env Vars
export KUBECONFIG=~/.kube/config
export GPG_TTY=$TTY
export PGPORT=5432;
